import type { ShapeKind } from "types/store.types"

/** same order as Paint's gallery. */
export const SHAPE_ORDER: ShapeKind[] = [
	"line",
	"curve",
	"oval",
	"rect",
	"rounded-rect",
	"polygon",
	"right-triangle",
	"triangle",
	"diamond",
	"pentagon",
	"hexagon",
	"arrow-right",
	"arrow-left",
	"arrow-up",
	"arrow-down",
	"star-4",
	"star-5",
	"star-6",
	"callout-rounded",
	"callout-oval",
	"callout-cloud",
	"heart",
	"lightning",
]

export const SHAPE_LABEL_KEYS: Record<ShapeKind, string> = {
	line: "ribbon.shapes.line",
	curve: "ribbon.shapes.curve",
	oval: "ribbon.shapes.oval",
	rect: "ribbon.shapes.rect",
	"rounded-rect": "ribbon.shapes.rounded-rect",
	polygon: "ribbon.shapes.polygon",
	"right-triangle": "ribbon.shapes.right-triangle",
	triangle: "ribbon.shapes.triangle",
	diamond: "ribbon.shapes.diamond",
	pentagon: "ribbon.shapes.pentagon",
	hexagon: "ribbon.shapes.hexagon",
	"arrow-right": "ribbon.shapes.arrow-right",
	"arrow-left": "ribbon.shapes.arrow-left",
	"arrow-up": "ribbon.shapes.arrow-up",
	"arrow-down": "ribbon.shapes.arrow-down",
	"star-4": "ribbon.shapes.star-4",
	"star-5": "ribbon.shapes.star-5",
	"star-6": "ribbon.shapes.star-6",
	"callout-rounded": "ribbon.shapes.callout-rounded",
	"callout-oval": "ribbon.shapes.callout-oval",
	"callout-cloud": "ribbon.shapes.callout-cloud",
	heart: "ribbon.shapes.heart",
	lightning: "ribbon.shapes.lightning",
}
